apiVersion: v1
kind: Endpoints
metadata:
  name: svc1
subsets:
  - addresses:
      - ip: 216.58.220.195  # đây là IP Google
    ports:
      - port: 80            # Lưu ý cần dấu "-" để chỉ là mảng
        protocol: TCP       # Giao thức (có thể là TCP hoặc UDP, TCP là mặc định nếu không chỉ định)
